import type { ReleaseCandidate } from "@/types/release";

/** Polished seeded demo — hero story is RC-104 blocked on missing/failed evidence. */
export const SEED_RELEASES: ReleaseCandidate[] = [
  {
    id: "rc-104",
    slug: "rc-104",
    name: "Checkout rewrite",
    version: "v2.4.0-rc.1",
    repository: "acme/commerce",
    branch: "release/checkout-rewrite",
    prNumber: 812,
    prUrl: "https://github.com/acme/commerce/pull/812",
    owner: "Maya Chen",
    targetEnv: "production",
    status: "BLOCKED",
    risk: "high",
    riskClasses: ["payments", "auth-surface", "breaking-api"],
    summary:
      "Rewrites checkout to a single-page flow with wallet pay. Blocked until failed E2E and missing experience/launch evidence are resolved or explicitly waived.",
    blockers: [
      "E2E suite failed on wallet pay path",
      "Preview accessibility evidence missing",
      "Rollback runbook not attached",
    ],
    warnings: ["Load test sample size below policy threshold"],
    updatedAt: "2026-07-11T02:41:00.000Z",
    createdAt: "2026-07-10T15:10:00.000Z",
    evidence: [
      {
        id: "ev-104-intent-1",
        group: "intent",
        title: "Linear intent + acceptance",
        summary:
          "SHE-204 Checkout rewrite — acceptance criteria linked and marked Ready for review.",
        status: "pass",
        required: true,
        owner: "Jordan Lee",
        sourceKind: "linear",
        sourceLabel: "SHE-204",
        sourceUrl: "https://linear.app/acme/issue/SHE-204",
        collectedAt: "2026-07-10T16:02:00.000Z",
        refreshedAt: "2026-07-11T01:10:00.000Z",
      },
      {
        id: "ev-104-eng-1",
        group: "engineering",
        title: "GitHub PR checks",
        summary: "Required status checks green on PR #812 (typecheck, lint, unit).",
        status: "pass",
        required: true,
        owner: "Maya Chen",
        sourceKind: "github",
        sourceLabel: "PR #812 checks",
        sourceUrl: "https://github.com/acme/commerce/pull/812/checks",
        collectedAt: "2026-07-11T01:55:00.000Z",
        refreshedAt: "2026-07-11T02:40:00.000Z",
      },
      {
        id: "ev-104-eng-2",
        group: "engineering",
        title: "E2E suite",
        summary:
          "Playwright wallet-pay path failed 3/3 runs on staging preview (timeout on confirm).",
        status: "fail",
        required: true,
        owner: "Sam Ortiz",
        sourceKind: "ci",
        sourceLabel: "CI · e2e-wallet",
        sourceUrl: "https://github.com/acme/commerce/actions/runs/991201",
        collectedAt: "2026-07-11T02:18:00.000Z",
        refreshedAt: "2026-07-11T02:38:00.000Z",
      },
      {
        id: "ev-104-exp-1",
        group: "experience",
        title: "Preview accessibility pass",
        summary:
          "No axe / keyboard evidence attached for the checkout preview URL.",
        status: "missing",
        required: true,
        owner: "Avery Kim",
        sourceKind: "manual",
        sourceLabel: "Not captured",
        collectedAt: "2026-07-10T15:10:00.000Z",
      },
      {
        id: "ev-104-exp-2",
        group: "experience",
        title: "Visual QA on preview",
        summary: "Desktop + mobile screenshots reviewed for happy path only.",
        status: "pass",
        required: false,
        owner: "Avery Kim",
        sourceKind: "manual",
        sourceLabel: "Manual capture",
        collectedAt: "2026-07-11T00:22:00.000Z",
      },
      {
        id: "ev-104-dep-1",
        group: "deployment",
        title: "Vercel preview deploy",
        summary: "Preview Ready · https://commerce-git-checkout-acme.vercel.app",
        status: "pass",
        required: true,
        owner: "Maya Chen",
        sourceKind: "vercel",
        sourceLabel: "Preview dpl_8f2a",
        sourceUrl: "https://commerce-git-checkout-acme.vercel.app",
        collectedAt: "2026-07-11T01:58:00.000Z",
        refreshedAt: "2026-07-11T02:40:00.000Z",
      },
      {
        id: "ev-104-dep-2",
        group: "deployment",
        title: "Load test sample",
        summary: "p95 OK but only 180 samples (policy asks ≥500 for payments).",
        status: "pending",
        required: false,
        owner: "Sam Ortiz",
        sourceKind: "ci",
        sourceLabel: "k6 · checkout",
        collectedAt: "2026-07-11T02:05:00.000Z",
      },
      {
        id: "ev-104-launch-1",
        group: "launch",
        title: "Rollback runbook",
        summary: "Required for high-risk payments releases — not attached.",
        status: "missing",
        required: true,
        owner: "Maya Chen",
        sourceKind: "manual",
        sourceLabel: "Not captured",
        collectedAt: "2026-07-10T15:10:00.000Z",
      },
      {
        id: "ev-104-launch-2",
        group: "launch",
        title: "Support / comms brief",
        summary: "Draft posted in #launch-checkout; awaiting owner sign-off.",
        status: "pending",
        required: false,
        owner: "Riley Fox",
        sourceKind: "manual",
        sourceLabel: "Notion draft",
        collectedAt: "2026-07-11T01:05:00.000Z",
      },
    ],
    recentActivity: [
      {
        id: "act-104-1",
        at: "2026-07-11T02:41:00.000Z",
        actor: "Policy engine",
        summary: "Recomputed decision → BLOCKED (3 required gaps).",
      },
      {
        id: "act-104-2",
        at: "2026-07-11T02:38:00.000Z",
        actor: "Sam Ortiz",
        summary: "Refreshed E2E suite evidence — still failing.",
      },
      {
        id: "act-104-3",
        at: "2026-07-11T01:58:00.000Z",
        actor: "Vercel adapter",
        summary: "Preview deploy Ready for PR #812.",
      },
    ],
    auditTrail: [
      {
        id: "aud-104-1",
        at: "2026-07-10T15:10:00.000Z",
        actor: "Maya Chen",
        kind: "created",
        summary: "Created release candidate RC-104 · Checkout rewrite",
        immutable: true,
      },
      {
        id: "aud-104-2",
        at: "2026-07-11T01:10:00.000Z",
        actor: "Linear adapter",
        kind: "evidence_refreshed",
        summary: "Refreshed intent evidence from SHE-204",
        immutable: true,
      },
      {
        id: "aud-104-3",
        at: "2026-07-11T02:18:00.000Z",
        actor: "CI adapter",
        kind: "evidence_refreshed",
        summary: "E2E suite marked fail",
        detail: "wallet-pay confirm timeout ×3",
        immutable: true,
      },
      {
        id: "aud-104-4",
        at: "2026-07-11T02:41:00.000Z",
        actor: "Policy engine",
        kind: "status_recomputed",
        summary: "Decision set to BLOCKED",
        detail:
          "Missing/failed required: E2E suite, Preview accessibility pass, Rollback runbook",
        immutable: true,
      },
    ],
  },
  {
    id: "rc-103",
    slug: "rc-103",
    name: "Pricing page refresh",
    version: "v2.3.2",
    repository: "acme/marketing",
    branch: "main",
    prNumber: 441,
    prUrl: "https://github.com/acme/marketing/pull/441",
    owner: "Riley Fox",
    targetEnv: "production",
    status: "READY",
    risk: "low",
    riskClasses: ["content-only"],
    summary: "Copy and layout refresh on /pricing. All required evidence green.",
    blockers: [],
    warnings: [],
    updatedAt: "2026-07-10T21:12:00.000Z",
    createdAt: "2026-07-09T18:00:00.000Z",
    evidence: [
      {
        id: "ev-103-intent-1",
        group: "intent",
        title: "Linear intent + acceptance",
        summary: "SHE-188 Pricing refresh — Done.",
        status: "pass",
        required: true,
        owner: "Riley Fox",
        sourceKind: "linear",
        sourceLabel: "SHE-188",
        sourceUrl: "https://linear.app/acme/issue/SHE-188",
        collectedAt: "2026-07-09T19:00:00.000Z",
      },
      {
        id: "ev-103-eng-1",
        group: "engineering",
        title: "GitHub PR checks",
        summary: "All required checks passed on PR #441.",
        status: "pass",
        required: true,
        owner: "Riley Fox",
        sourceKind: "github",
        sourceLabel: "PR #441 checks",
        sourceUrl: "https://github.com/acme/marketing/pull/441/checks",
        collectedAt: "2026-07-10T20:40:00.000Z",
      },
      {
        id: "ev-103-exp-1",
        group: "experience",
        title: "Preview accessibility pass",
        summary: "Manual keyboard pass + axe clean on preview.",
        status: "pass",
        required: true,
        owner: "Avery Kim",
        sourceKind: "manual",
        sourceLabel: "Manual capture",
        collectedAt: "2026-07-10T20:55:00.000Z",
      },
      {
        id: "ev-103-dep-1",
        group: "deployment",
        title: "Vercel preview deploy",
        summary: "Preview Ready.",
        status: "pass",
        required: true,
        owner: "Riley Fox",
        sourceKind: "vercel",
        sourceLabel: "Preview dpl_1aa0",
        sourceUrl: "https://marketing-git-pricing-acme.vercel.app",
        collectedAt: "2026-07-10T20:42:00.000Z",
      },
      {
        id: "ev-103-launch-1",
        group: "launch",
        title: "Rollback runbook",
        summary: "Content revert via CMS — documented.",
        status: "pass",
        required: false,
        owner: "Riley Fox",
        sourceKind: "manual",
        sourceLabel: "Runbook",
        collectedAt: "2026-07-10T21:00:00.000Z",
      },
    ],
    recentActivity: [
      {
        id: "act-103-1",
        at: "2026-07-10T21:12:00.000Z",
        actor: "Policy engine",
        summary: "Decision READY — all required evidence pass.",
      },
      {
        id: "act-103-2",
        at: "2026-07-10T20:55:00.000Z",
        actor: "Avery Kim",
        summary: "Captured preview accessibility evidence.",
      },
    ],
    auditTrail: [
      {
        id: "aud-103-1",
        at: "2026-07-09T18:00:00.000Z",
        actor: "Riley Fox",
        kind: "created",
        summary: "Created release candidate RC-103 · Pricing page refresh",
        immutable: true,
      },
      {
        id: "aud-103-2",
        at: "2026-07-10T21:12:00.000Z",
        actor: "Policy engine",
        kind: "status_recomputed",
        summary: "Decision set to READY",
        immutable: true,
      },
      {
        id: "aud-103-3",
        at: "2026-07-10T21:20:00.000Z",
        actor: "Jordan Lee",
        kind: "approved",
        summary: "Approved for production",
        detail: "Low-risk content change; evidence complete.",
        immutable: true,
      },
    ],
  },
  {
    id: "rc-102",
    slug: "rc-102",
    name: "Auth session hotfix",
    version: "v2.3.1",
    repository: "acme/commerce",
    branch: "hotfix/session-ttl",
    prNumber: 798,
    prUrl: "https://github.com/acme/commerce/pull/798",
    owner: "Sam Ortiz",
    targetEnv: "production",
    status: "WARNING",
    risk: "medium",
    riskClasses: ["auth-surface"],
    summary:
      "Shortens session TTL. Approved with exception for incomplete load-test evidence.",
    blockers: [],
    warnings: ["Load test waived via exception"],
    updatedAt: "2026-07-09T14:30:00.000Z",
    createdAt: "2026-07-09T09:00:00.000Z",
    evidence: [
      {
        id: "ev-102-intent-1",
        group: "intent",
        title: "Linear intent + acceptance",
        summary: "SHE-176 Session TTL hotfix.",
        status: "pass",
        required: true,
        owner: "Sam Ortiz",
        sourceKind: "linear",
        sourceLabel: "SHE-176",
        sourceUrl: "https://linear.app/acme/issue/SHE-176",
        collectedAt: "2026-07-09T09:20:00.000Z",
      },
      {
        id: "ev-102-eng-1",
        group: "engineering",
        title: "GitHub PR checks",
        summary: "Required checks passed.",
        status: "pass",
        required: true,
        owner: "Sam Ortiz",
        sourceKind: "github",
        sourceLabel: "PR #798 checks",
        sourceUrl: "https://github.com/acme/commerce/pull/798/checks",
        collectedAt: "2026-07-09T12:10:00.000Z",
      },
      {
        id: "ev-102-exp-1",
        group: "experience",
        title: "Preview accessibility pass",
        summary: "No UI surface change — marked N/A pass.",
        status: "pass",
        required: true,
        owner: "Avery Kim",
        sourceKind: "manual",
        sourceLabel: "Manual capture",
        collectedAt: "2026-07-09T12:40:00.000Z",
      },
      {
        id: "ev-102-dep-1",
        group: "deployment",
        title: "Vercel preview deploy",
        summary: "Preview Ready.",
        status: "pass",
        required: true,
        owner: "Sam Ortiz",
        sourceKind: "vercel",
        sourceLabel: "Preview dpl_77c1",
        collectedAt: "2026-07-09T12:12:00.000Z",
      },
      {
        id: "ev-102-dep-2",
        group: "deployment",
        title: "Load test sample",
        summary: "Waived — hotfix window; monitor post-deploy.",
        status: "waived",
        required: false,
        owner: "Jordan Lee",
        sourceKind: "policy",
        sourceLabel: "Exception",
        collectedAt: "2026-07-09T14:28:00.000Z",
      },
      {
        id: "ev-102-launch-1",
        group: "launch",
        title: "Rollback runbook",
        summary: "Revert PR #798 documented.",
        status: "pass",
        required: true,
        owner: "Sam Ortiz",
        sourceKind: "manual",
        sourceLabel: "Runbook",
        collectedAt: "2026-07-09T13:00:00.000Z",
      },
    ],
    recentActivity: [
      {
        id: "act-102-1",
        at: "2026-07-09T14:30:00.000Z",
        actor: "Jordan Lee",
        summary: "Approved with exception — load test waived.",
      },
    ],
    auditTrail: [
      {
        id: "aud-102-1",
        at: "2026-07-09T09:00:00.000Z",
        actor: "Sam Ortiz",
        kind: "created",
        summary: "Created release candidate RC-102 · Auth session hotfix",
        immutable: true,
      },
      {
        id: "aud-102-2",
        at: "2026-07-09T14:30:00.000Z",
        actor: "Jordan Lee",
        kind: "approved_with_exception",
        summary: "Approved with exception",
        detail:
          "Waive load test for hotfix window; watch auth error rate for 2h post-deploy.",
        immutable: true,
      },
    ],
  },
];

export const DEMO_ACTOR = "You (demo owner)";
export const DEMO_WORKSPACE = "Acme · Private MVP";
